### ISSUE TITLE
XmlParser buildEmployeesData 

### ISSUE THREAD

**Issue by makiame** [alex-nzr/bit-umc-php-sdk#3]
если у сотрудника указана только 1 услуга в основных услугах, то парсер ее пропускает. 

если услуги 2 то ```$item[$servicesKey][$oneServiceKey]``` - это  массив с ключами 0, 1 и т.д 
![image](https://github.com/user-attachments/assets/c504409d-e181-4f41-9824-5d4d3cc5140b)

если услуга 1, то это будет ассоциативный массив с ключами UID и Duration (типа ```$item[$servicesKey][$oneServiceKey]["UID"]```)

для пример вот мой быстрый фикс)) 
 if (count($item[$servicesKey][$oneServiceKey]) === 2 && isset($item[$servicesKey][$oneServiceKey]['UID'])) {
              if (key_exists($serviceUidKey, $item[$servicesKey][$oneServiceKey]) && !empty($item[$servicesKey][$oneServiceKey][$serviceUidKey]))
              {
                  $employee['services'][$item[$servicesKey][$oneServiceKey][$serviceUidKey]] = [
                      'uid'              => $item[$servicesKey][$oneServiceKey][$serviceUidKey],
                      'personalDuration' => strtotime($item[$servicesKey][$oneServiceKey][$durationKey])-strtotime('0001-01-01T00:00:00')
                  ];
              }
          } else {
              foreach ($item[$servicesKey][$oneServiceKey] as $service)
              {
                  if (is_array($service) && key_exists($serviceUidKey, $service) && !empty($service[$serviceUidKey]))
                  {
                      $employee['services'][$service[$serviceUidKey]] = [
                          'uid'              => $service[$serviceUidKey],
                          'personalDuration' => strtotime($service[$durationKey])-strtotime('0001-01-01T00:00:00')
                      ];
                  }
              }

**Comment by alex-nzr** [comment]
Спасибо. Аналогичная проблема присутствует у клиник, у сотрудников, у услуг и у расписания и везде эта ситуация обработана. Но вот именно услуги внутри сотрудника я упустил)
Исправил, сделал релиз с фиксом.
